### ISSUE TITLE
Integration using Homie convention

### ISSUE THREAD

**Issue by michaelfung** [mongoose-os-apps/sonoff-basic-openhab2#1]
Hi Sergio,

Thanks for improving the app! And also I will try to add Homie support to my original app. Hope you don't mind if I shamelessly copy some of your code.

Thanks,
Michael

**Comment by scaprile** [comment]
Hi Michael, no problem at all, I copied all of yours.
Do you think we can integrate both into one ? I kept them separate because there may be some users of the 1.x binding that could benefit from your approach.
Cheers.

**Comment by michaelfung** [comment]
Sure, I plan to put the init script in a separate folder. Thanks!
